# Generated by Django 3.2 on 2021-04-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210429_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='create_by',
        ),
    ]
