# Generated by Django 3.2 on 2021-04-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True)),
                ('gender', models.CharField(max_length=1)),
                ('hire_date', models.DateField(blank=True)),
                ('type', models.CharField(choices=[('chef', 'Chef'), ('waiter', 'Waiter'), ('bartender', 'Bartender'), ('kitchen_assistant', 'Kitchen Assistant'), ('manager', 'Manager'), ('helper', 'Helper'), ('author', 'Author')], max_length=20)),
            ],
        ),
    ]
