# Generated by Django 3.2 on 2021-04-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('chef', 'Chef'), ('waiter', 'Waiter'), ('bartender', 'Bartender'), ('kitchen_assistant', 'Kitchen Assistant'), ('manager', 'Manager'), ('helper', 'Helper'), ('author', 'Author')], default='helper', max_length=20),
        ),
    ]
