# Generated by Django 3.2 on 2021-04-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
